config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books do
    resources :transactions, only: [:new, :create, :show]
  end
  resources :profiles, except: [:index, :destroy] do
    resources :transactions, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
  validates :name, presence: true
  validates :author, presence: true
  validates :language, presence: true
  validates :number_of_pages, presence: true
  validates :edition, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validates :photo, presence: true
  validates :genre, presence: true
  mount_uploader :photo, PhotoUploader

  include PgSearch::Model
  pg_search_scope :search_by_book_feature,
    against: [ :name, :author, :language, :description, :edition ],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :borrow_date, presence: true
  validates :return_date, presence: true
  validate :borrow_date_starting_today
  validate :validate_other_booking_overlap

  private

  def borrow_date_starting_today
    return if return_date.blank? || borrow_date.blank?

      if borrow_date < Date.today
        errors.add(:borrow_date, "cannot be in the past.")
      end
  end

  def validate_other_booking_overlap
    sql = ":book_id = book_id and :return_date >= borrow_date and return_date >= :borrow_date"
    is_overlapping = Transaction.where(sql, book_id: book_id, borrow_date: borrow_date, return_date: return_date).exists?
    errors.add(:borrow_date, "isn't valid. This book won't be available in the period you chose. Please choose another date.") if is_overlapping
  end
end

# sql = ":book.id = book.id and :return_date >= borrow_date and return_date >= :borrow_date"
# is_overlapping = Transaction.where(sql, book_id: book_id, borrow_date: Date.new(2019, 8, 30), return_date: Date.new(2019, 9, 8)).exists?

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :transactions
  has_one :profile, dependent: :destroy
  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only:[:index, :show]
  before_action :fetch_book, only:[:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @results = policy_scope(Book).order(:created_at).search_by_book_feature(params[:query])
    else
      @results = policy_scope(Book).order(created_at: :desc)
    end
  end

  def show
    @book = Book.find(params[:id])
    @transaction = Transaction.new
    @results = Book.search_by_book_feature(params[:query])
  end

  def new
    @book = Book.new
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    authorize @book
    @book.user = current_user
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to books_path
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def fetch_book
    @book = Book.find(params[:id])
    authorize @book
  end

  def book_params
    params.require(:book).permit(:name, :description, :author, :photo, :number_of_pages, :language, :edition, :genre)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @results = Book.search_by_book_feature(params[:query])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    # @user = current_user
    # @profile = Profile.find(params[@user])
    @user = current_user
    @profile = current_user.profile
    authorize @profile
  end

  def new
    @user = current_user
    @profile = Profile.new
    # @profile = current_user.profile.new
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    authorize @profile
    @profile.user = current_user
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :address, :phone_number, :photo)

  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :fetch_book, except: [:index]

  def index
    @transactions = Transaction.all
  end

  def new
    @transaction = Transaction.new
    authorize @transaction
  end

  def create
    @transaction = Transaction.new(transaction_params) # user_id, book_id
    authorize @transaction
    @transaction.user = current_user
    @transaction.book = @book
    @transaction.return_date = @transaction.borrow_date + 10
    # raise
    if @transaction.save
      render :show
    else
      render 'books/show'
    end
  end

  def show
    @transaction = Transaction.find(params[:transaction_id])
    authorize @transaction
    @book = @transaction.book
  end

  private

  def transaction_params
    params.require(:transaction).permit(:borrow_date, :return_date, :book_id)
  end

  def fetch_book
    @book = Book.find(params[:book_id])
  end

  def fetch_profile
    @user = User.find(params[:profile_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<div class="container mb-4">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-lg-6">
      <h2>Add a book</h2>
      <br>
      <%= simple_form_for @book do |f| %>
        <%#= f.error_notification %>

        <% if @book.errors.any? %>
         <div class="alert alert-danger">
            <h3>Please fix these problems:</h3>
            <ul>
            <% @book.errors.full_messages.each do |error| %>
              <li><%= error %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-inputs">
          <%= f.input :name, :error => false %>
          <%= f.input :author, :error => false %>
          <%= f.input :number_of_pages, :error => false %>
          <%= f.input :description, :error => false %>
          <%= f.input :language, :error => false %>
          <%= f.input :genre, :error => false %>
          <%= f.input :edition, :error => false %>
          <%= f.input :photo, :error => false %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Create this book", class: 'btn btn-dark rounded-pill', data: {confirm: "Create this book?"} %>
        </div>
      <% end %>
      <br>
      <%= link_to "Back to Books", books_path, class: 'btn btn-outline-secondary rounded-pill' %>
    </div>
  </div>
</div>

app/views/books/after_checkout.html.erb
<div class="jumbotron text-center">
  <h3 class="display-3">Thank You for borrowing the book, <%=User.email %> </h3>
  <p class="lead"><strong>Please check your email</strong> You can get your book starting at <%=Date.today%> until <%=Date.today + 2%>. After receiving, You will have 10 days to return this book after confimation</p>
  <hr>
  <p>
    <a href="">Contact us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="http://localhost:3000/books/" role="button">Back to books list</a>
  </p>
</div>

app/views/books/edit.html.erb
<div class="container mb-4">
  <%= simple_form_for @book do |f| %>
    <%#= f.error_notification %>

    <% if @book.errors.any? %>
     <div class="alert alert-danger">
        <h3>Please fix these problems:</h3>
        <ul>
        <% @book.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-inputs">
      <%= f.input :name, :error => false %>
      <%= f.input :author, :error => false %>
      <%= f.input :number_of_pages, :error => false %>
      <%= f.input :description, :error => false %>
      <%= f.input :language, :error => false %>
      <%= f.input :genre, :error => false %>
      <%= f.input :edition, :error => false %>
      <%= f.input :photo, :error => false %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Update this book", class: 'btn btn-dark rounded-pill', data: {confirm: "Update this book?"} %>
    </div>
  <% end %>
  <br>
  <%= link_to "Back to Books", books_path, class: 'btn btn-outline-secondary rounded-pill' %>
</div>

app/views/books/index.html.erb
<div class="index-page">
  <div class="d-flex justify-content-between">
    <%= render 'shared/search' %>

      <div class="btn-add">
        <%= link_to "Add a book", new_book_path, class: 'btn btn-secondary rounded-pill' %>
      </div>
  </div>


  <h4>Browse the Shelf</h4>


  <% if @results.empty? %>
    <h6><%= "Sorry, this book doesn't exist in this plataform." %></h6>
  <% else %>
    <div class="row">
    <% @results.each do |result|  %>

      <div class="col-xs-12 col-sm-12 col-md-6">
        <%= link_to book_path(result), method: :get, :action => 'go' do %>
          <div class="card-product">
            <img src= "<%= result.photo %>" />

            <div class="card-product-infos">
              <h5><%=result.name%>, <%=result.author%></h5>
              <p><%=result.description%></p>
              <p><%=result.language%></p>
              <p>Edition: <%=result.edition%></p>
              <p><%=result.genre%></p>
            </div>

            <div class='icon d-flex justify-content-end'>
              <% if policy(result).edit? %>
                <i class="fas fa-user"></i>
              <% end %>
            </div>



          </div>
          <% end %>
      </div>
    <% end %>
    </div>

  <% end %>
</div>



 <%#@books.each do |book|  %>

  <%#= link_to book_path(book), :action => 'go' do %>
    <!-- <div class="card-product"> -->
      <!-- <img src= "<%#= book.photo %>" /> -->
      <!-- <div class="card-product-infos"> -->
        <!-- <h2><%#=book.name%>, <%#=book.author%></h2> -->
         <!-- <p><%#=book.description%></p> -->
       <!-- </div>
     </div> -->
     <%# end %>
   <%#end%>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<%= render 'shared/search' %>
<%= render 'shared/search_results' %>


<div class="show-card">
  <div class="content-backgroud">

    <img src="<%= @book.photo %>" />

    <div class="show-card-infos">
       <div class='icons d-flex justify-content-end'>

        <div id='trash'>
          <% if policy(@book).destroy? %>
            <%= link_to book_path(@book), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </div>

        <div id='pencil'>
          <% if policy(@book).edit? %>
            <%= link_to edit_book_path(@book) do %>
              <i class="fas fa-pencil-alt"></i>
            <% end %>
          <% end %>
        </div>

      </div>



      <h2><%=@book.name%></h2>
      <h3><%=@book.author%></h3>
      <p>Edition: <%=@book.edition%></p>
      <p>Language: <%=@book.language%></p>
      <p>Genre: <%=@book.genre%></p>
      <p>Pages: <%=@book.number_of_pages%></p>
      <p>Sinopse: <%=@book.description%></p>
<br>
      <%#= link_to "Borrow this book!", book_transactions_path(@book), method: :post, class: 'btn btn-dark rounded-pill' %>
      <%= render '/transactions/form'%>


    </div>
  </div>
  <div class="button-back">
    <%= link_to "Back to List", books_path, class: 'btn btn-outline-secondary rounded-pill' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap" rel="stylesheet">
    <title>Shared Shelf</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if params[:controller] == "pages" %>
    <div class="homepage-content">
    <% else %>
    <div class="site-content">
    <% end %>
      <%= yield %>
    </div>


    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1479142506502-19b3a3b7ff33?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">

  <div class="container">
    <div class="tag-line">
      <h1>Welcome to the Shared Shelf</h1>
      <h3>Borrow books you love</h3>
    </div>
    <!-- <h3>Find books you love</h3> -->
    <div class="position-search">
      <div class="home-search-form  form-inline">
        <%= form_tag books_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a book"
           %>
            <%= submit_tag "Search", class: "btn-search" %>
    <% end %>
  </div>
      <%= render 'shared/search_results' %>
    </div>
  </div>
</div>

<div class="downArrow bounce">
  <img width="50px" height="50px" alt="" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjwhRE9DVFlQRSBzdmcgIFBVQkxJQyAnLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4nICAnaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkJz48c3ZnIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDMyIDMyIiBoZWlnaHQ9IjMycHgiIGlkPSLQodC70L7QuV8xIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjMycHgiIHhtbDpzcGFjZT0icHJlc2VydmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxwYXRoIGQ9Ik0yNC4yODUsMTEuMjg0TDE2LDE5LjU3MWwtOC4yODUtOC4yODhjLTAuMzk1LTAuMzk1LTEuMDM0LTAuMzk1LTEuNDI5LDAgIGMtMC4zOTQsMC4zOTUtMC4zOTQsMS4wMzUsMCwxLjQzbDguOTk5LDkuMDAybDAsMGwwLDBjMC4zOTQsMC4zOTUsMS4wMzQsMC4zOTUsMS40MjgsMGw4Ljk5OS05LjAwMiAgYzAuMzk0LTAuMzk1LDAuMzk0LTEuMDM2LDAtMS40MzFDMjUuMzE5LDEwLjg4OSwyNC42NzksMTAuODg5LDI0LjI4NSwxMS4yODR6IiBmaWxsPSIjMTIxMzEzIiBpZD0iRXhwYW5kX01vcmUiLz48Zy8+PGcvPjxnLz48Zy8+PGcvPjxnLz48L3N2Zz4=" />
</div>


<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <%= link_to books_path, :action => 'go' do %>
        <div class="carousel-item active ">
              <img src="https://images.unsplash.com/photo-1507842217343-583bb7270b66?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1453&q=80" class="d-block w-100" alt="shelf">
              <div class="carousel-caption d-none d-md-block carousel-text-background">
                <h4>Browse the Shelf</h4>
                <p>Find all books you can borrow</p>
              </div>
      <% end %>
      </div>

      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1497633762265-9d179a990aa6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80" class="d-block w-100" alt="books">
        <div class="carousel-caption d-none d-md-block carousel-text-background">
          <h4>Browse by genre</h4>
          <p>Find the genres you love</p>
        </div>
      </div>

      <div class="carousel-item">
        <img src="https://images.unsplash.com/photo-1474366521946-c3d4b507abf2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" class="d-block w-100" alt="table">
        <div class="carousel-caption d-none d-md-block carousel-text-background">
          <h4>Read reviews</h4>
          <p>See other readers opinion</p>
        </div>
      </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>
</div>

app/views/profiles/new.html.erb
<div class="new-profile form-control col-sm-6">
<%= simple_form_for @profile do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :photo %>
  <%= f.submit "create/update", class: "btn btn-primary" %>
<% end %>
</div>

app/views/profiles/show.html.erb
<div class="profile-page">
    <div class="profile-welcame">
          <h2>Hello, <%=@profile.first_name %>!</h2>
          <h3> <%#=@profile.photo %></h3>
    </div>

      <h4>Your borrowing history:</h4>


          <div class="row">
          <% @user.transactions.each do |transaction| %>

            <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="profile-card-product">
                  <img src= "<%= transaction.book.photo %>" />
                  <div class="profile-card-product-infos">
                    Book: <%= transaction.book.name %>, Borrowing Date: <%= transaction.borrow_date %>, Return Date: <%= transaction.return_date %>
                  </div>
                </div>
            </div>
            <% end %>
        </div>

      <h4>Your lending history:</h4>
        <p>Please authorize or decline your pending requests.</p>

   <div class="row">
      <% @user.books.each do |book| %>
        <% book.transactions.each do |book_transactions| %>
          <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="profile-card-product">
              <img src= "<%= book_transactions.book.photo %>" />
              <div class="profile-card-product-infos">
                Book: <%= book_transactions.book.name %>, Requested Borrow Date: <%= book_transactions.borrow_date %>, Requested Return Date: <%= book_transactions.return_date %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/183/183334.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active nav-link">
          <%= "" %>
        </li>
        <li class="nav-item">
          <%#= link_to "", "#", class: "nav-link" %>
          <%= link_to "#{current_user.email}", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://images.unsplash.com/photo-1548532928-b34e3be62fc6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2067&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
               <% if current_user.profile.present? %>
               <%= link_to "Profile", profile_path(current_user.profile), class: "dropdown-item" %>
               <% else %>
                <%= link_to "Profile", new_profile_path, class: "dropdown-item" %>
              <% end %>
            <% end %>
            <%= link_to "Settings", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item mr-2">
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary rounded-pill" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-dark rounded-pill" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
    <div class="search-form  form-inline">
    <%= form_tag books_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a book"
       %>
        <%= submit_tag "Search", class: "btn-search" %>
    <% end %>
  </div>

app/views/shared/_search_results.html.erb
<% if not @results.nil? %>
  <% @results.each do |result|  %>
    <%= link_to book_path(result), method: :get, :action => 'go' do %>
      <div class="card-product">
        <img src= "<%= result.photo %>" />
        <div class="card-product-infos">
          <h2><%=result.name%>, <%=result.author%></h2>
          <p><%=result.description%></p>
          <p><%=result.language%></p>
          <p><%=result.publishing_year%></p>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/transactions/_form.html.erb
<%= simple_form_for [@book, @transaction] do |f| %>
  <%#= f.error_notification %>

  <% if @transaction.errors.any? %>
   <div class="alert alert-danger">
      <h3>Please fix these problems:</h3>
      <ul>
      <% @transaction.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :borrow_date, :error => false %>
    <%#= f.input :return_date, as: :date, selected: Date.today + 10, as: :hidden%>
    <%#= f.input :book_id, as: :hidden, value: @book.id %>
    <%#= f.input :user_id, as: :hidden, value: current_user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Borrow this book", class: 'btn btn-dark rounded-pill', data: {confirm: "Confirm book borrowing?"} %>
  </div>
  <p>You can keep this book during 10 days, starting from the borrowing date!</p>
<% end %>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/show.html.erb
<div class="jumbotron text-center">
  <h3>Thank you for borrowing the book <strong><em><%= @book.name %></em></strong>, <%=@transaction.user.email %>!</h3>
  <h3>Enjoy your reading!</h3>
  <h4>Please make sure you return the book by <%= @transaction.return_date %>.</h4>
  <p class="lead">Check your email for additional details.</p>
  <hr class="my-4">
  <p>
    <a href="">Contact us</a>
  </p>
  <p class="lead">
    <%= link_to 'Back to books list', books_path, class: "btn btn-dark rounded-pill"%>
  </p>
</div>